/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import DAO.TaiKhoanDAO;
import Entity.TaiKhoan;
import Helper.Auth;
import Helper.MsgBox;
import java.awt.Color;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.font.TextAttribute;
import java.util.Map;
import javax.swing.BorderFactory;

/**
 *
 * @author Trần Trung Nghĩa <PS14820>
 */
public class DangNhapJDialog extends javax.swing.JDialog {

        /**
         * Creates new form DangNhapJDialog
         */
        public DangNhapJDialog(java.awt.Frame parent, boolean modal) {
                super(parent, modal);
                initComponents();
                setLocationRelativeTo(null);
                setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/icons/logo1.png")));
                setResizable(false);
                init();

        }

        void init() {
                setLocationRelativeTo(null);
        }
        TaiKhoanDAO tkDAO = new TaiKhoanDAO();

        public void login() {
                if (Auth.user != null) {
                        MsgBox.alert(this, "Đăng nhập thành công !");
                        this.dispose();
                } else {
                        if (txtTenDangNhap.getText().trim().isEmpty()) {
                                MsgBox.alert(this, "Nhập tên tài khoản !");
                                txtTenDangNhap.requestFocus();
                                return;
                        }
                        if (txtMatKhau.getText().trim().isEmpty()) {
                                MsgBox.alert(this, "Nhập mật khẩu !");
                                txtMatKhau.requestFocus();
                                return;
                        }

                        String tenDangNhap = txtTenDangNhap.getText();
                        String matKhau = new String(txtMatKhau.getPassword());

                        TaiKhoan tk = tkDAO.SelectByID(tenDangNhap);
                        if (tk == null) {
                                MsgBox.alert(this, "Sai tên đăng nhập !");
                        } else if (!matKhau.equals(tk.getMatKhau())) {
                                MsgBox.alert(this, "Sai tên mật khẩu !");
                        } else {
                                Auth.user = tk;
                                MsgBox.alert(this, "Đăng nhập thành công !");
                                this.dispose();
                        }
                }
        }

        /**
         * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel2 = new javax.swing.JPanel();
                jLabel2 = new javax.swing.JLabel();
                jLabel1 = new javax.swing.JLabel();
                txtTenDangNhap = new javax.swing.JTextField();
                jLabel3 = new javax.swing.JLabel();
                txtMatKhau = new javax.swing.JPasswordField();
                chkHienMatKhau = new javax.swing.JCheckBox();
                btnDangNhap = new javax.swing.JButton();
                btnThoat = new javax.swing.JButton();
                lblQRCode = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                lblClose = new javax.swing.JLabel();
                background = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
                setTitle("GodEdoc_Đăng Nhập");
                setUndecorated(true);

                jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
                jLabel2.setForeground(new java.awt.Color(255, 255, 255));
                jLabel2.setText("Tài khoản");
                jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, -1));

                jLabel1.setForeground(new java.awt.Color(255, 255, 255));
                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ver2.png"))); // NOI18N
                jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

                txtTenDangNhap.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
                txtTenDangNhap.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyPressed(java.awt.event.KeyEvent evt) {
                                txtTenDangNhapKeyPressed(evt);
                        }
                });
                jPanel2.add(txtTenDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 236, -1));

                jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
                jLabel3.setForeground(new java.awt.Color(255, 255, 255));
                jLabel3.setText("Mật khẩu");
                jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, -1));

                txtMatKhau.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
                txtMatKhau.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyPressed(java.awt.event.KeyEvent evt) {
                                txtMatKhauKeyPressed(evt);
                        }
                });
                jPanel2.add(txtMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 235, -1));

                chkHienMatKhau.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
                chkHienMatKhau.setForeground(new java.awt.Color(255, 255, 255));
                chkHienMatKhau.setText("Hiển thị mật khẩu");
                chkHienMatKhau.addChangeListener(new javax.swing.event.ChangeListener() {
                        public void stateChanged(javax.swing.event.ChangeEvent evt) {
                                chkHienMatKhauStateChanged(evt);
                        }
                });
                chkHienMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseEntered(java.awt.event.MouseEvent evt) {
                                chkHienMatKhauMouseEntered(evt);
                        }
                        public void mouseExited(java.awt.event.MouseEvent evt) {
                                chkHienMatKhauMouseExited(evt);
                        }
                });
                chkHienMatKhau.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyPressed(java.awt.event.KeyEvent evt) {
                                chkHienMatKhauKeyPressed(evt);
                        }
                });
                jPanel2.add(chkHienMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, -1, -1));

                btnDangNhap.setBackground(new java.awt.Color(255, 0, 0));
                btnDangNhap.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                btnDangNhap.setForeground(new java.awt.Color(255, 255, 255));
                btnDangNhap.setText("Đăng nhập");
                btnDangNhap.setBorderPainted(false);
                btnDangNhap.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseEntered(java.awt.event.MouseEvent evt) {
                                btnDangNhapMouseEntered(evt);
                        }
                        public void mouseExited(java.awt.event.MouseEvent evt) {
                                btnDangNhapMouseExited(evt);
                        }
                });
                btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnDangNhapActionPerformed(evt);
                        }
                });
                btnDangNhap.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyPressed(java.awt.event.KeyEvent evt) {
                                btnDangNhapKeyPressed(evt);
                        }
                });
                jPanel2.add(btnDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 235, 40));

                btnThoat.setBackground(new java.awt.Color(0, 0, 0));
                btnThoat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                btnThoat.setForeground(new java.awt.Color(255, 255, 255));
                btnThoat.setText("Thoát");
                btnThoat.setBorderPainted(false);
                btnThoat.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseEntered(java.awt.event.MouseEvent evt) {
                                btnThoatMouseEntered(evt);
                        }
                        public void mouseExited(java.awt.event.MouseEvent evt) {
                                btnThoatMouseExited(evt);
                        }
                });
                btnThoat.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnThoatActionPerformed(evt);
                        }
                });
                jPanel2.add(btnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 236, 40));

                lblQRCode.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
                lblQRCode.setForeground(new java.awt.Color(255, 255, 255));
                lblQRCode.setText("QR Code");
                lblQRCode.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lblQRCodeMouseClicked(evt);
                        }
                        public void mouseEntered(java.awt.event.MouseEvent evt) {
                                lblQRCodeMouseEntered(evt);
                        }
                        public void mouseExited(java.awt.event.MouseEvent evt) {
                                lblQRCodeMouseExited(evt);
                        }
                });
                jPanel2.add(lblQRCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, -1, -1));

                jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
                jLabel4.setForeground(new java.awt.Color(255, 0, 0));
                jLabel4.setText("ĐĂNG NHẬP");
                jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, -1));

                lblClose.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
                lblClose.setForeground(new java.awt.Color(255, 255, 255));
                lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/remove.png"))); // NOI18N
                lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lblCloseMouseClicked(evt);
                        }
                        public void mouseEntered(java.awt.event.MouseEvent evt) {
                                lblCloseMouseEntered(evt);
                        }
                        public void mouseExited(java.awt.event.MouseEvent evt) {
                                lblCloseMouseExited(evt);
                        }
                });
                jPanel2.add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 40, 40));

                background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/loginJDialog.png"))); // NOI18N
                jPanel2.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 440));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void chkHienMatKhauMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkHienMatKhauMouseEntered
                // TODO add your handling code here:
                chkHienMatKhau.setForeground(Color.RED);
                Font font = chkHienMatKhau.getFont();
                Map attributes = font.getAttributes();
                attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
                chkHienMatKhau.setFont(font.deriveFont(attributes));
        }//GEN-LAST:event_chkHienMatKhauMouseEntered

        private void chkHienMatKhauMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkHienMatKhauMouseExited
                // TODO add your handling code here:
                chkHienMatKhau.setForeground(new Color(255, 255, 255));
                Font font = chkHienMatKhau.getFont();
                Map attributes = font.getAttributes();
                attributes.put(TextAttribute.UNDERLINE, -1);
                chkHienMatKhau.setFont(font.deriveFont(attributes));
        }//GEN-LAST:event_chkHienMatKhauMouseExited

        private void btnDangNhapMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDangNhapMouseEntered
                // TODO add your handling code here:
                btnDangNhap.setBorder(BorderFactory.createMatteBorder(10, 10, 10, 10, Color.WHITE));
                Font font = btnDangNhap.getFont();
                Map attributes = font.getAttributes();
                attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
                btnDangNhap.setFont(font.deriveFont(attributes));
                btnDangNhap.setBackground(new Color(255, 102, 102));
        }//GEN-LAST:event_btnDangNhapMouseEntered

        private void btnDangNhapMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDangNhapMouseExited
                // TODO add your handling code here:
                btnDangNhap.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLACK));
                Font font = btnDangNhap.getFont();
                Map attributes = font.getAttributes();
                attributes.put(TextAttribute.UNDERLINE, -1);
                btnDangNhap.setFont(font.deriveFont(attributes));
                btnDangNhap.setBackground(new Color(255, 0, 0));
        }//GEN-LAST:event_btnDangNhapMouseExited

        private void btnThoatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThoatMouseEntered
                // TODO add your handling code here:
                btnThoat.setBorder(BorderFactory.createMatteBorder(5, 5, 5, 5, Color.WHITE));
                btnThoat.setForeground(Color.RED);
                Font font = btnThoat.getFont();
                Map attributes = font.getAttributes();
                attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
                btnThoat.setFont(font.deriveFont(attributes));
        }//GEN-LAST:event_btnThoatMouseEntered

        private void btnThoatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThoatMouseExited
                // TODO add your handling code here:
                btnThoat.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLACK));
                btnThoat.setForeground(Color.WHITE);
                Font font = btnThoat.getFont();
                Map attributes = font.getAttributes();
                attributes.put(TextAttribute.UNDERLINE, -1);
                btnThoat.setFont(font.deriveFont(attributes));
        }//GEN-LAST:event_btnThoatMouseExited

        private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
                // TODO add your handling code here:
                login();
        }//GEN-LAST:event_btnDangNhapActionPerformed

        private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
                // TODO add your handling code here:
                if (MsgBox.confirm(this, "Bạn có chắc muốn đóng ?")) {
                        System.exit(0);
                }
        }//GEN-LAST:event_btnThoatActionPerformed

        private void lblQRCodeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQRCodeMouseEntered
                // TODO add your handling code here:
                lblQRCode.setForeground(Color.RED);
                Font font = lblQRCode.getFont();
                Map attributes = font.getAttributes();
                attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
                lblQRCode.setFont(font.deriveFont(attributes));
        }//GEN-LAST:event_lblQRCodeMouseEntered

        private void lblQRCodeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQRCodeMouseExited
                // TODO add your handling code here:
                lblQRCode.setForeground(Color.WHITE);
                Font font = lblQRCode.getFont();
                Map attributes = font.getAttributes();
                attributes.put(TextAttribute.UNDERLINE, -1);
                lblQRCode.setFont(font.deriveFont(attributes));
        }//GEN-LAST:event_lblQRCodeMouseExited

        private void lblQRCodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQRCodeMouseClicked
                // TODO add your handling code here:
                this.dispose();
                Scan_QR_CODE dialog = new Scan_QR_CODE(new javax.swing.JFrame(), true);
                dialog.setVisible(true);
        }//GEN-LAST:event_lblQRCodeMouseClicked

        private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
                // TODO add your handling code here:
                System.exit(0);
        }//GEN-LAST:event_lblCloseMouseClicked

        private void lblCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseEntered
                // TODO add your handling code here:
                lblClose.setForeground(Color.RED);
        }//GEN-LAST:event_lblCloseMouseEntered

        private void lblCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseExited
                // TODO add your handling code here:
                lblClose.setForeground(Color.WHITE);
        }//GEN-LAST:event_lblCloseMouseExited

        private void chkHienMatKhauStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkHienMatKhauStateChanged
                // TODO add your handling code here:
                if (chkHienMatKhau.isSelected()) {
                        txtMatKhau.setEchoChar((char) 0);
                } else {
                        txtMatKhau.setEchoChar('*');
                }
        }//GEN-LAST:event_chkHienMatKhauStateChanged

        private void txtTenDangNhapKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenDangNhapKeyPressed
                // TODO add your handling code here:

                if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                        // Enter was pressed. Your code goes here.
                        login();
                }
        }//GEN-LAST:event_txtTenDangNhapKeyPressed

        private void txtMatKhauKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMatKhauKeyPressed
                // TODO add your handling code here:
                if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                        // Enter was pressed. Your code goes here.
                        login();
                }
        }//GEN-LAST:event_txtMatKhauKeyPressed

        private void btnDangNhapKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnDangNhapKeyPressed
                // TODO add your handling code here:
                if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                        // Enter was pressed. Your code goes here.
                        login();
                }
        }//GEN-LAST:event_btnDangNhapKeyPressed

        private void chkHienMatKhauKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chkHienMatKhauKeyPressed
                // TODO add your handling code here:
                if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                        // Enter was pressed. Your code goes here.
                        login();
                }
        }//GEN-LAST:event_chkHienMatKhauKeyPressed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(DangNhapJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(DangNhapJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(DangNhapJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(DangNhapJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
                //</editor-fold>

                /* Create and display the dialog */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                DangNhapJDialog dialog = new DangNhapJDialog(new javax.swing.JFrame(), true);
                                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                                        @Override
                                        public void windowClosing(java.awt.event.WindowEvent e) {
                                                System.exit(0);
                                        }
                                });
                                dialog.setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel background;
        private javax.swing.JButton btnDangNhap;
        private javax.swing.JButton btnThoat;
        private javax.swing.JCheckBox chkHienMatKhau;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JLabel lblClose;
        private javax.swing.JLabel lblQRCode;
        private javax.swing.JPasswordField txtMatKhau;
        private javax.swing.JTextField txtTenDangNhap;
        // End of variables declaration//GEN-END:variables
}
