/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import CHAT.LoginFrame;
import DAO.NhanVienDAO;
import Entity.NhanVien;
import Helper.Auth;
import Helper.MsgBox;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author Trần Trung Nghĩa <PS14820>
 */
public class GiaoDienChinhJFrame extends javax.swing.JFrame {

        /**
         * Creates new form GiaoDienChinhJFrame
         */
        public GiaoDienChinhJFrame() {
                initComponents();
                setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/icons/logo1.png")));
                new ChaoJDialog(this, true).setVisible(true);
                new DangNhapJDialog(this, true).setVisible(true);
                initHienThongTin();
                init();
                this.startDongHo();
        }

        void init() {
                setLocationRelativeTo(null);
                setResizable(false);
                pnlChucNang.setBackground(new Color(247, 220, 111, 95));
                pnlAdmin.setBackground(new Color(247, 220, 111, 95));
                pnlNhanSu.setBackground(new Color(247, 220, 111, 95));
                pnlKS.setBackground(new Color(247, 220, 111, 95));
                pnlLeTan.setBackground(new Color(247, 220, 111, 95));
                pnlThongTinAccount.setBackground(new Color(247, 220, 111, 200));

        }

        void startDongHo() {
                SimpleDateFormat formater = new SimpleDateFormat("hh:mm:ss a");
                new Timer(1000, (ActionEvent e) -> {
                        lblDongHo.setText(formater.format(new Date()));
                }).start();
        }

        /**
         * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                pnlThongTinAccount = new javax.swing.JPanel();
                pnlHinhAnh = new javax.swing.JPanel();
                jlable = new javax.swing.JLabel();
                jlabel = new javax.swing.JLabel();
                lblTenTaiKhoan = new javax.swing.JLabel();
                lblChucVu = new javax.swing.JLabel();
                lblHinhAnh = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                pnlChucNang = new javax.swing.JPanel();
                pnlAdmin = new javax.swing.JPanel();
                lblPhong = new javax.swing.JLabel();
                lblKhachHang = new javax.swing.JLabel();
                lblTaiKhoan = new javax.swing.JLabel();
                lblDichVu = new javax.swing.JLabel();
                lblThongKe = new javax.swing.JLabel();
                lblDoThatLac = new javax.swing.JLabel();
                lblNhanVien = new javax.swing.JLabel();
                lblKhoHang = new javax.swing.JLabel();
                pnlNhanSu = new javax.swing.JPanel();
                lblNhanVienNS = new javax.swing.JLabel();
                lblDangXuatNS = new javax.swing.JLabel();
                lblTaiKhoanNS = new javax.swing.JLabel();
                lblDoiMatKhau = new javax.swing.JLabel();
                pnlLeTan = new javax.swing.JPanel();
                lblKhachHangLT = new javax.swing.JLabel();
                lblDangXuatLT = new javax.swing.JLabel();
                lblDichVuLT = new javax.swing.JLabel();
                lblDatPhongLT = new javax.swing.JLabel();
                lblThanhToanLT = new javax.swing.JLabel();
                lblFeedBackLT = new javax.swing.JLabel();
                lblDoiMatKhau1 = new javax.swing.JLabel();
                pnlKS = new javax.swing.JPanel();
                lblDangXuatKS = new javax.swing.JLabel();
                lblKhachHangKS = new javax.swing.JLabel();
                lblPhongKS = new javax.swing.JLabel();
                lblThongKeKS = new javax.swing.JLabel();
                lblDichVuKS = new javax.swing.JLabel();
                lblDoThatLacQLKS = new javax.swing.JLabel();
                lblDoiMatKhau2 = new javax.swing.JLabel();
                lblKhoHang1 = new javax.swing.JLabel();
                lblbackgr = new javax.swing.JLabel();
                jLabel1 = new javax.swing.JLabel();
                lblDongHo = new javax.swing.JLabel();
                jMenuBar1 = new javax.swing.JMenuBar();
                mnuHeThong = new javax.swing.JMenu();
                mniDoiMatKhau = new javax.swing.JMenuItem();
                mniThoat = new javax.swing.JMenuItem();
                mniDangXuat = new javax.swing.JMenuItem();
                mnuTroGiup = new javax.swing.JMenu();
                mniThongTinPhanMem = new javax.swing.JMenuItem();
                mniChat = new javax.swing.JMenu();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("God Edoc Hotel");

                jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                pnlHinhAnh.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jlable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                jlable.setForeground(new java.awt.Color(17, 26, 41));
                jlable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/privacy.png"))); // NOI18N
                jlable.setText("Mã Nhân Viên:");

                jlabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                jlabel.setForeground(new java.awt.Color(17, 26, 41));
                jlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/job.png"))); // NOI18N
                jlabel.setText("Chức Vụ:");

                lblTenTaiKhoan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                lblTenTaiKhoan.setForeground(new java.awt.Color(17, 26, 41));
                lblTenTaiKhoan.setText("TK04");

                lblChucVu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                lblChucVu.setForeground(new java.awt.Color(17, 26, 41));
                lblChucVu.setText("Giám Đốc");

                lblHinhAnh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

                jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/avatar.png"))); // NOI18N
                jLabel2.setText("Avatar");

                javax.swing.GroupLayout pnlThongTinAccountLayout = new javax.swing.GroupLayout(pnlThongTinAccount);
                pnlThongTinAccount.setLayout(pnlThongTinAccountLayout);
                pnlThongTinAccountLayout.setHorizontalGroup(
                        pnlThongTinAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pnlHinhAnh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlThongTinAccountLayout.createSequentialGroup()
                                .addGroup(pnlThongTinAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pnlThongTinAccountLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(pnlThongTinAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(pnlThongTinAccountLayout.createSequentialGroup()
                                                                .addComponent(jlabel)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(lblChucVu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addGroup(pnlThongTinAccountLayout.createSequentialGroup()
                                                                .addComponent(jlable)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(lblTenTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(pnlThongTinAccountLayout.createSequentialGroup()
                                                                .addGap(64, 64, 64)
                                                                .addComponent(lblHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(pnlThongTinAccountLayout.createSequentialGroup()
                                                .addGap(110, 110, 110)
                                                .addComponent(jLabel2)))
                                .addContainerGap(17, Short.MAX_VALUE))
                );
                pnlThongTinAccountLayout.setVerticalGroup(
                        pnlThongTinAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlThongTinAccountLayout.createSequentialGroup()
                                .addComponent(pnlHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlThongTinAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jlable)
                                        .addComponent(lblTenTaiKhoan))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlThongTinAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jlabel)
                                        .addComponent(lblChucVu))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                jPanel1.add(pnlThongTinAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 330, 390));

                pnlChucNang.setLayout(new java.awt.CardLayout());

                lblPhong.setBackground(new Color(247, 220, 111, 95));
                lblPhong.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                lblPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/single-bed.png"))); // NOI18N
                lblPhong.setText("PHÒNG");
                lblPhong.setVerticalAlignment(javax.swing.SwingConstants.TOP);
                lblPhong.setFocusable(false);
                lblPhong.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                lblPhong.setOpaque(true);
                lblPhong.setVerifyInputWhenFocusTarget(false);
                lblPhong.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
                lblPhong.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lblPhongMouseClicked(evt);
                        }
                });

                lblKhachHang.setBackground(new Color(247, 220, 111, 95));
                lblKhachHang.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                lblKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/guests.png"))); // NOI18N
                lblKhachHang.setText("KHÁCH HÀNG");
                lblKhachHang.setVerticalAlignment(javax.swing.SwingConstants.TOP);
                lblKhachHang.setFocusable(false);
                lblKhachHang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                lblKhachHang.setOpaque(true);
                lblKhachHang.setVerifyInputWhenFocusTarget(false);
                lblKhachHang.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
                lblKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lblKhachHangMouseClicked(evt);
                        }
                });

                lblTaiKhoan.setBackground(new Color(247, 220, 111, 95));
                lblTaiKhoan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                lblTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ac.png"))); // NOI18N
                lblTaiKhoan.setText("TÀI KHOẢN");
                lblTaiKhoan.setVerticalAlignment(javax.swing.SwingConstants.TOP);
                lblTaiKhoan.setFocusable(false);
                lblTaiKhoan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                lblTaiKhoan.setOpaque(true);
                lblTaiKhoan.setVerifyInputWhenFocusTarget(false);
                lblTaiKhoan.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
                lblTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lblTaiKhoanMouseClicked(evt);
                        }
                });

                lblDichVu.setBackground(new Color(247, 220, 111, 95));
                lblDichVu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                lblDichVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/reception.png"))); // NOI18N
                lblDichVu.setText("DỊCH VỤ");
                lblDichVu.setVerticalAlignment(javax.swing.SwingConstants.TOP);
                lblDichVu.setFocusable(false);
                lblDichVu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                lblDichVu.setOpaque(true);
                lblDichVu.setVerifyInputWhenFocusTarget(false);
                lblDichVu.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
                lblDichVu.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lblDichVuMouseClicked(evt);
                        }
                });

                lblThongKe.setBackground(new Color(247, 220, 111, 95));
                lblThongKe.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                lblThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/analytics.png"))); // NOI18N
                lblThongKe.setText("THỐNG KÊ");
                lblThongKe.setVerticalAlignment(javax.swing.SwingConstants.TOP);
                lblThongKe.setFocusable(false);
                lblThongKe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                lblThongKe.setOpaque(true);
                lblThongKe.setVerifyInputWhenFocusTarget(false);
                lblThongKe.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
                lblThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lblThongKeMouseClicked(evt);
                        }
                });

                lblDoThatLac.setBackground(new Color(247, 220, 111, 95));
                lblDoThatLac.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                lblDoThatLac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/suitcase.png"))); // NOI18N
                lblDoThatLac.setText("ĐỒ THẤT LẠC");
                lblDoThatLac.setVerticalAlignment(javax.swing.SwingConstants.TOP);
                lblDoThatLac.setFocusable(false);
                lblDoThatLac.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                lblDoThatLac.setOpaque(true);
                lblDoThatLac.setVerifyInputWhenFocusTarget(false);
                lblDoThatLac.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
                lblDoThatLac.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lblDoThatLacMouseClicked(evt);
                        }
                });

                lblNhanVien.setBackground(new Color(247, 220, 111, 95));
                lblNhanVien.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                lblNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/support.png"))); // NOI18N
                lblNhanVien.setText("NHÂN VIÊN");
                lblNhanVien.setVerticalAlignment(javax.swing.SwingConstants.TOP);
                lblNhanVien.setFocusable(false);
                lblNhanVien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                lblNhanVien.setOpaque(true);
                lblNhanVien.setVerifyInputWhenFocusTarget(false);
                lblNhanVien.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
                lblNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lblNhanVienMouseClicked(evt);
                        }
                });

                lblKhoHang.setBackground(new Color(247, 220, 111, 95));
                lblKhoHang.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                lblKhoHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/depot.png"))); // NOI18N
                lblKhoHang.setText("Kho Hàng");
                lblKhoHang.setVerticalAlignment(javax.swing.SwingConstants.TOP);
                lblKhoHang.setFocusable(false);
                lblKhoHang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                lblKhoHang.setOpaque(true);
                lblKhoHang.setVerifyInputWhenFocusTarget(false);
                lblKhoHang.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
                lblKhoHang.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lblKhoHangMouseClicked(evt);
                        }
                });

                javax.swing.GroupLayout pnlAdminLayout = new javax.swing.GroupLayout(pnlAdmin);
                pnlAdmin.setLayout(pnlAdminLayout);
                pnlAdminLayout.setHorizontalGroup(
                        pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlAdminLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(pnlAdminLayout.createSequentialGroup()
                                                .addComponent(lblPhong)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblNhanVien)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblKhachHang)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(pnlAdminLayout.createSequentialGroup()
                                                .addComponent(lblDichVu)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblThongKe)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblDoThatLac, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblKhoHang)))
                                .addContainerGap())
                );
                pnlAdminLayout.setVerticalGroup(
                        pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlAdminLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblTaiKhoan)
                                        .addComponent(lblKhachHang)
                                        .addComponent(lblPhong)
                                        .addComponent(lblNhanVien))
                                .addGap(18, 18, 18)
                                .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblDichVu)
                                        .addComponent(lblThongKe)
                                        .addComponent(lblDoThatLac)
                                        .addComponent(lblKhoHang))
                                .addContainerGap())
                );

                pnlChucNang.add(pnlAdmin, "card2");

                lblNhanVienNS.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                lblNhanVienNS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/support.png"))); // NOI18N
                lblNhanVienNS.setText("NHÂN VIÊN");
                lblNhanVienNS.setVerticalAlignment(javax.swing.SwingConstants.TOP);
                lblNhanVienNS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                lblNhanVienNS.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
                lblNhanVienNS.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lblNhanVienNSMouseClicked(evt);
                        }
                });

                lblDangXuatNS.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                lblDangXuatNS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout (2).png"))); // NOI18N
                lblDangXuatNS.setText("ĐĂNG XUẤT");
                lblDangXuatNS.setVerticalAlignment(javax.swing.SwingConstants.TOP);
                lblDangXuatNS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                lblDangXuatNS.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
                lblDangXuatNS.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lblDangXuatNSMouseClicked(evt);
                        }
                });

                lblTaiKhoanNS.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                lblTaiKhoanNS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ac.png"))); // NOI18N
                lblTaiKhoanNS.setText("TÀI KHOẢN");
                lblTaiKhoanNS.setVerticalAlignment(javax.swing.SwingConstants.TOP);
                lblTaiKhoanNS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                lblTaiKhoanNS.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
                lblTaiKhoanNS.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lblTaiKhoanNSMouseClicked(evt);
                        }
                });

                lblDoiMatKhau.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                lblDoiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/password.png"))); // NOI18N
                lblDoiMatKhau.setText("ĐỔI MẬT KHẨU");
                lblDoiMatKhau.setVerticalAlignment(javax.swing.SwingConstants.TOP);
                lblDoiMatKhau.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                lblDoiMatKhau.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
                lblDoiMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lblDoiMatKhauMouseClicked(evt);
                        }
                });

                javax.swing.GroupLayout pnlNhanSuLayout = new javax.swing.GroupLayout(pnlNhanSu);
                pnlNhanSu.setLayout(pnlNhanSuLayout);
                pnlNhanSuLayout.setHorizontalGroup(
                        pnlNhanSuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNhanSuLayout.createSequentialGroup()
                                .addContainerGap(96, Short.MAX_VALUE)
                                .addGroup(pnlNhanSuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblDoiMatKhau)
                                        .addComponent(lblNhanVienNS, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(100, 100, 100)
                                .addGroup(pnlNhanSuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblTaiKhoanNS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblDangXuatNS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(128, 128, 128))
                );
                pnlNhanSuLayout.setVerticalGroup(
                        pnlNhanSuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlNhanSuLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(pnlNhanSuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblTaiKhoanNS, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblNhanVienNS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addGroup(pnlNhanSuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblDoiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblDangXuatNS, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                );

                pnlChucNang.add(pnlNhanSu, "card3");

                lblKhachHangLT.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                lblKhachHangLT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/guests.png"))); // NOI18N
                lblKhachHangLT.setText("KHÁCH HÀNG");
                lblKhachHangLT.setVerticalAlignment(javax.swing.SwingConstants.TOP);
                lblKhachHangLT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                lblKhachHangLT.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
                lblKhachHangLT.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lblKhachHangLTMouseClicked(evt);
                        }
                });

                lblDangXuatLT.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                lblDangXuatLT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout (2).png"))); // NOI18N
                lblDangXuatLT.setText("ĐĂNG XUẤT");
                lblDangXuatLT.setVerticalAlignment(javax.swing.SwingConstants.TOP);
                lblDangXuatLT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                lblDangXuatLT.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
                lblDangXuatLT.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lblDangXuatLTMouseClicked(evt);
                        }
                });

                lblDichVuLT.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                lblDichVuLT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/reception.png"))); // NOI18N
                lblDichVuLT.setText("DỊCH VỤ");
                lblDichVuLT.setVerticalAlignment(javax.swing.SwingConstants.TOP);
                lblDichVuLT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                lblDichVuLT.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
                lblDichVuLT.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lblDichVuLTMouseClicked(evt);
                        }
                });

                lblDatPhongLT.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                lblDatPhongLT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/medical-history.png"))); // NOI18N
                lblDatPhongLT.setText("ĐẶT PHÒNG");
                lblDatPhongLT.setVerticalAlignment(javax.swing.SwingConstants.TOP);
                lblDatPhongLT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                lblDatPhongLT.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
                lblDatPhongLT.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lblDatPhongLTMouseClicked(evt);
                        }
                });

                lblThanhToanLT.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                lblThanhToanLT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/credit-card.png"))); // NOI18N
                lblThanhToanLT.setText("THANH TOÁN");
                lblThanhToanLT.setVerticalAlignment(javax.swing.SwingConstants.TOP);
                lblThanhToanLT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                lblThanhToanLT.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
                lblThanhToanLT.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lblThanhToanLTMouseClicked(evt);
                        }
                });

                lblFeedBackLT.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                lblFeedBackLT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/rating.png"))); // NOI18N
                lblFeedBackLT.setText("FEEDBACK");
                lblFeedBackLT.setVerticalAlignment(javax.swing.SwingConstants.TOP);
                lblFeedBackLT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                lblFeedBackLT.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
                lblFeedBackLT.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lblFeedBackLTMouseClicked(evt);
                        }
                });

                lblDoiMatKhau1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                lblDoiMatKhau1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/password.png"))); // NOI18N
                lblDoiMatKhau1.setText("ĐỔI MẬT KHẨU");
                lblDoiMatKhau1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
                lblDoiMatKhau1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                lblDoiMatKhau1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
                lblDoiMatKhau1.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lblDoiMatKhau1MouseClicked(evt);
                        }
                });

                javax.swing.GroupLayout pnlLeTanLayout = new javax.swing.GroupLayout(pnlLeTan);
                pnlLeTan.setLayout(pnlLeTanLayout);
                pnlLeTanLayout.setHorizontalGroup(
                        pnlLeTanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlLeTanLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnlLeTanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblDatPhongLT)
                                        .addComponent(lblKhachHangLT))
                                .addGap(18, 18, 18)
                                .addGroup(pnlLeTanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(pnlLeTanLayout.createSequentialGroup()
                                                .addComponent(lblDichVuLT)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblThanhToanLT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(pnlLeTanLayout.createSequentialGroup()
                                                .addComponent(lblFeedBackLT)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblDangXuatLT)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblDoiMatKhau1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                pnlLeTanLayout.setVerticalGroup(
                        pnlLeTanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlLeTanLayout.createSequentialGroup()
                                .addGroup(pnlLeTanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pnlLeTanLayout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addGroup(pnlLeTanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(lblDichVuLT)
                                                        .addComponent(lblDatPhongLT)
                                                        .addComponent(lblThanhToanLT))
                                                .addGap(18, 18, 18)
                                                .addGroup(pnlLeTanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lblFeedBackLT)
                                                        .addComponent(lblDangXuatLT)
                                                        .addComponent(lblKhachHangLT)))
                                        .addGroup(pnlLeTanLayout.createSequentialGroup()
                                                .addGap(105, 105, 105)
                                                .addComponent(lblDoiMatKhau1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(20, 20, 20))
                );

                pnlChucNang.add(pnlLeTan, "card4");

                lblDangXuatKS.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                lblDangXuatKS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lblDangXuatKS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout (2).png"))); // NOI18N
                lblDangXuatKS.setText("ĐĂNG XUẤT");
                lblDangXuatKS.setVerticalAlignment(javax.swing.SwingConstants.TOP);
                lblDangXuatKS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                lblDangXuatKS.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
                lblDangXuatKS.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lblDangXuatKSMouseClicked(evt);
                        }
                });

                lblKhachHangKS.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                lblKhachHangKS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lblKhachHangKS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/guests.png"))); // NOI18N
                lblKhachHangKS.setText("KHÁCH HÀNG");
                lblKhachHangKS.setVerticalAlignment(javax.swing.SwingConstants.TOP);
                lblKhachHangKS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                lblKhachHangKS.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
                lblKhachHangKS.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lblKhachHangKSMouseClicked(evt);
                        }
                });

                lblPhongKS.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                lblPhongKS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lblPhongKS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/single-bed.png"))); // NOI18N
                lblPhongKS.setText("PHÒNG");
                lblPhongKS.setVerticalAlignment(javax.swing.SwingConstants.TOP);
                lblPhongKS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                lblPhongKS.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
                lblPhongKS.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lblPhongKSMouseClicked(evt);
                        }
                });

                lblThongKeKS.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                lblThongKeKS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lblThongKeKS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/analytics.png"))); // NOI18N
                lblThongKeKS.setText("THỐNG KÊ");
                lblThongKeKS.setVerticalAlignment(javax.swing.SwingConstants.TOP);
                lblThongKeKS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                lblThongKeKS.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
                lblThongKeKS.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lblThongKeKSMouseClicked(evt);
                        }
                });

                lblDichVuKS.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                lblDichVuKS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lblDichVuKS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/reception.png"))); // NOI18N
                lblDichVuKS.setText("DỊCH VỤ");
                lblDichVuKS.setVerticalAlignment(javax.swing.SwingConstants.TOP);
                lblDichVuKS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                lblDichVuKS.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
                lblDichVuKS.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lblDichVuKSMouseClicked(evt);
                        }
                });

                lblDoThatLacQLKS.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                lblDoThatLacQLKS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lblDoThatLacQLKS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/suitcase.png"))); // NOI18N
                lblDoThatLacQLKS.setText("ĐỒ THẤT LẠC");
                lblDoThatLacQLKS.setVerticalAlignment(javax.swing.SwingConstants.TOP);
                lblDoThatLacQLKS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                lblDoThatLacQLKS.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
                lblDoThatLacQLKS.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lblDoThatLacQLKSMouseClicked(evt);
                        }
                });

                lblDoiMatKhau2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                lblDoiMatKhau2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/password.png"))); // NOI18N
                lblDoiMatKhau2.setText("ĐỔI MẬT KHẨU");
                lblDoiMatKhau2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
                lblDoiMatKhau2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                lblDoiMatKhau2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
                lblDoiMatKhau2.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lblDoiMatKhau2MouseClicked(evt);
                        }
                });

                lblKhoHang1.setBackground(new Color(247, 220, 111, 95));
                lblKhoHang1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
                lblKhoHang1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/depot.png"))); // NOI18N
                lblKhoHang1.setText("Kho Hàng");
                lblKhoHang1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
                lblKhoHang1.setFocusable(false);
                lblKhoHang1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                lblKhoHang1.setOpaque(true);
                lblKhoHang1.setVerifyInputWhenFocusTarget(false);
                lblKhoHang1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
                lblKhoHang1.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lblKhoHang1MouseClicked(evt);
                        }
                });

                javax.swing.GroupLayout pnlKSLayout = new javax.swing.GroupLayout(pnlKS);
                pnlKS.setLayout(pnlKSLayout);
                pnlKSLayout.setHorizontalGroup(
                        pnlKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlKSLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnlKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(pnlKSLayout.createSequentialGroup()
                                                .addComponent(lblPhongKS, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblThongKeKS, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(pnlKSLayout.createSequentialGroup()
                                                .addComponent(lblDichVuKS, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblDoThatLacQLKS, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(pnlKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pnlKSLayout.createSequentialGroup()
                                                .addComponent(lblDangXuatKS, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblKhoHang1))
                                        .addGroup(pnlKSLayout.createSequentialGroup()
                                                .addComponent(lblKhachHangKS, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblDoiMatKhau2)))
                                .addGap(14, 14, 14))
                );
                pnlKSLayout.setVerticalGroup(
                        pnlKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlKSLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(pnlKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pnlKSLayout.createSequentialGroup()
                                                .addGroup(pnlKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lblKhachHangKS, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lblDoiMatKhau2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(pnlKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(lblDangXuatKS, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lblKhoHang1))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(pnlKSLayout.createSequentialGroup()
                                                .addGroup(pnlKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lblPhongKS, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lblThongKeKS, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(pnlKSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lblDichVuKS, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lblDoThatLacQLKS, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(20, 20, 20))))
                );

                pnlChucNang.add(pnlKS, "card5");

                jPanel1.add(pnlChucNang, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 590, 360));

                lblbackgr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/fullHD_3.png"))); // NOI18N
                jPanel1.add(lblbackgr, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 570));

                jLabel1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/management (1).png"))); // NOI18N
                jLabel1.setText("HỆ THỐNG QUẢN LÝ KHÁCH SẠN GOD EDOC");

                lblDongHo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
                lblDongHo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/alarm-clock.png"))); // NOI18N
                lblDongHo.setText("12:12:12");

                mnuHeThong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/review (1).png"))); // NOI18N
                mnuHeThong.setText("Hệ thống");

                mniDoiMatKhau.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
                mniDoiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/lock.png"))); // NOI18N
                mniDoiMatKhau.setText("Đổi Mật Khẩu");
                mniDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                mniDoiMatKhauActionPerformed(evt);
                        }
                });
                mnuHeThong.add(mniDoiMatKhau);

                mniThoat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
                mniThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/1exit.png"))); // NOI18N
                mniThoat.setText("Thoát");
                mniThoat.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                mniThoatActionPerformed(evt);
                        }
                });
                mnuHeThong.add(mniThoat);

                mniDangXuat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
                mniDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Log out.png"))); // NOI18N
                mniDangXuat.setText("Đăng Xuất");
                mniDangXuat.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                mniDangXuatActionPerformed(evt);
                        }
                });
                mnuHeThong.add(mniDangXuat);

                jMenuBar1.add(mnuHeThong);

                mnuTroGiup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/solution.png"))); // NOI18N
                mnuTroGiup.setText("Hỗ Trợ");

                mniThongTinPhanMem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
                mniThongTinPhanMem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/application.png"))); // NOI18N
                mniThongTinPhanMem.setText("Thông Tin Phần Mềm");
                mniThongTinPhanMem.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                mniThongTinPhanMemActionPerformed(evt);
                        }
                });
                mnuTroGiup.add(mniThongTinPhanMem);

                jMenuBar1.add(mnuTroGiup);

                mniChat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/chat.png"))); // NOI18N
                mniChat.setText("Chat");
                mniChat.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                mniChatMouseClicked(evt);
                        }
                });
                jMenuBar1.add(mniChat);

                setJMenuBar(jMenuBar1);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblDongHo)
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                                        .addComponent(lblDongHo))
                                .addContainerGap())
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void lblPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPhongMouseClicked
            // TODO add your handling code here:
            if (Auth.user == null) {
                    MsgBox.alert(this, "Vui lòng đăng nhập để sử dụng chức năng !");
                    return;
            }
            new PhongJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_lblPhongMouseClicked

    private void lblKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKhachHangMouseClicked
            // TODO add your handling code here:
            if (Auth.user == null) {
                    MsgBox.alert(this, "Vui lòng đăng nhập để sử dụng chức năng !");
                    return;
            }
            new KhachHangJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_lblKhachHangMouseClicked

    private void lblTaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTaiKhoanMouseClicked
            // TODO add your handling code here:
            if (Auth.user == null) {
                    MsgBox.alert(this, "Vui lòng đăng nhập để sử dụng chức năng !");
                    return;
            }
            new DangKiTaiKhoanJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_lblTaiKhoanMouseClicked

    private void lblDichVuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDichVuMouseClicked
            // TODO add your handling code here:
            if (Auth.user == null) {
                    MsgBox.alert(this, "Vui lòng đăng nhập để sử dụng chức năng !");
                    return;
            }
            new QuanLyDichVuJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_lblDichVuMouseClicked

    private void lblThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThongKeMouseClicked
            // TODO add your handling code here:
            if (Auth.user == null) {
                    MsgBox.alert(this, "Vui lòng đăng nhập để sử dụng chức năng !");
                    return;
            }
            new ThongKeJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_lblThongKeMouseClicked

    private void lblNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNhanVienMouseClicked
            // TODO add your handling code here:
            if (Auth.user == null) {
                    MsgBox.alert(this, "Vui lòng đăng nhập để sử dụng chức năng !");
                    return;
            }
            new NhanVienJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_lblNhanVienMouseClicked

    private void lblKhoHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKhoHangMouseClicked
            // TODO add your handling code here:
            new KhoHangJdialog(this, true).setVisible(true);
            this.setVisible(true);
            initHienThongTin();
    }//GEN-LAST:event_lblKhoHangMouseClicked

    private void lblDoThatLacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoThatLacMouseClicked
            // TODO add your handling code here:
            if (Auth.user == null) {
                    MsgBox.alert(this, "Vui lòng đăng nhập để sử dụng chức năng !");
                    return;
            }
            new DoThatLacJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_lblDoThatLacMouseClicked

    private void lblNhanVienNSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNhanVienNSMouseClicked
            // TODO add your handling code here:
            if (Auth.user == null) {
                    MsgBox.alert(this, "Vui lòng đăng nhập để sử dụng chức năng !");
                    return;
            }
            new NhanVienJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_lblNhanVienNSMouseClicked

    private void lblDangXuatNSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDangXuatNSMouseClicked
            // TODO add your handling code here:
            lblHinhAnh.setIcon(null);
            Auth.user = null;
            this.dispose();
            new DangNhapJDialog(this, true).setVisible(true);
            this.setVisible(true);
            initHienThongTin();
    }//GEN-LAST:event_lblDangXuatNSMouseClicked

    private void lblTaiKhoanNSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTaiKhoanNSMouseClicked
            // TODO add your handling code here:
            if (Auth.user == null) {
                    MsgBox.alert(this, "Vui lòng đăng nhập để sử dụng chức năng !");
                    return;
            }
            new DangKiTaiKhoanJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_lblTaiKhoanNSMouseClicked

    private void lblDatPhongLTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDatPhongLTMouseClicked
            // TODO add your handling code here:
            if (Auth.user == null) {
                    MsgBox.alert(this, "Vui lòng đăng nhập để sử dụng chức năng !");
                    return;
            }
            new DatPhongJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_lblDatPhongLTMouseClicked

    private void lblDichVuLTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDichVuLTMouseClicked
            // TODO add your handling code here:
            if (Auth.user == null) {
                    MsgBox.alert(this, "Vui lòng đăng nhập để sử dụng chức năng !");
                    return;
            }
            new QuanLyDichVuJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_lblDichVuLTMouseClicked

    private void lblThanhToanLTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThanhToanLTMouseClicked
            // TODO add your handling code here:
            if (Auth.user == null) {
                    MsgBox.alert(this, "Vui lòng đăng nhập để sử dụng chức năng !");
                    return;
            }
            DatPhongJDialog dialog = new DatPhongJDialog(new javax.swing.JFrame(), true);
            dialog.jTabbedPane1.setSelectedIndex(3);
            dialog.setVisible(true);

    }//GEN-LAST:event_lblThanhToanLTMouseClicked

    private void lblKhachHangLTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKhachHangLTMouseClicked
            // TODO add your handling code here:
            if (Auth.user == null) {
                    MsgBox.alert(this, "Vui lòng đăng nhập để sử dụng chức năng !");
                    return;
            }
            new KhachHangJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_lblKhachHangLTMouseClicked

    private void lblFeedBackLTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFeedBackLTMouseClicked
            // TODO add your handling code here:
            try {
                    Desktop.getDesktop().browse(new File("web/Buoi_10/FeedBack.html").toURI());
            } catch (IOException ex) {
                    MsgBox.alert(this, "Không tìm thấy file hướng dẫn!");
            }
    }//GEN-LAST:event_lblFeedBackLTMouseClicked

    private void lblDangXuatLTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDangXuatLTMouseClicked
            // TODO add your handling code here:
            lblHinhAnh.setIcon(null);
            Auth.user = null;
            this.dispose();
            new DangNhapJDialog(this, true).setVisible(true);
            this.setVisible(true);
            initHienThongTin();
    }//GEN-LAST:event_lblDangXuatLTMouseClicked

    private void lblDangXuatKSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDangXuatKSMouseClicked
            // TODO add your handling code here:
            lblHinhAnh.setIcon(null);
            Auth.user = null;
            this.dispose();
            new DangNhapJDialog(this, true).setVisible(true);
            this.setVisible(true);
            initHienThongTin();
    }//GEN-LAST:event_lblDangXuatKSMouseClicked

    private void lblKhachHangKSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKhachHangKSMouseClicked
            // TODO add your handling code here:
            if (Auth.user == null) {
                    MsgBox.alert(this, "Vui lòng đăng nhập để sử dụng chức năng !");
                    return;
            }
            new KhachHangJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_lblKhachHangKSMouseClicked

    private void lblThongKeKSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThongKeKSMouseClicked
            // TODO add your handling code here:
            if (Auth.user == null) {
                    MsgBox.alert(this, "Vui lòng đăng nhập để sử dụng chức năng !");
                    return;
            }
            new ThongKeJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_lblThongKeKSMouseClicked

    private void lblPhongKSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPhongKSMouseClicked
            // TODO add your handling code here:
            if (Auth.user == null) {
                    MsgBox.alert(this, "Vui lòng đăng nhập để sử dụng chức năng !");
                    return;
            }
            new PhongJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_lblPhongKSMouseClicked

    private void lblDichVuKSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDichVuKSMouseClicked
            // TODO add your handling code here:
            if (Auth.user == null) {
                    MsgBox.alert(this, "Vui lòng đăng nhập để sử dụng chức năng !");
                    return;
            }
            new QuanLyDichVuJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_lblDichVuKSMouseClicked

    private void lblDoThatLacQLKSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoThatLacQLKSMouseClicked
            // TODO add your handling code here:
            if (Auth.user == null) {
                    MsgBox.alert(this, "Vui lòng đăng nhập để sử dụng chức năng !");
                    return;
            }
            new DoThatLacJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_lblDoThatLacQLKSMouseClicked

    private void lblDoiMatKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoiMatKhauMouseClicked
            // TODO add your handling code here:
            this.dispose();
            new DoiMatKhauJDialog(this, true).setVisible(true);
            this.setVisible(true);
//            initHienThongTin();

    }//GEN-LAST:event_lblDoiMatKhauMouseClicked

    private void lblDoiMatKhau1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoiMatKhau1MouseClicked
            // TODO add your handling code here:
            this.dispose();
            new DoiMatKhauJDialog(this, true).setVisible(true);
            this.setVisible(true);
            initHienThongTin();
    }//GEN-LAST:event_lblDoiMatKhau1MouseClicked

    private void lblDoiMatKhau2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoiMatKhau2MouseClicked
            // TODO add your handling code here:
            this.dispose();
            new DoiMatKhauJDialog(this, true).setVisible(true);
            this.setVisible(true);
            initHienThongTin();
    }//GEN-LAST:event_lblDoiMatKhau2MouseClicked

        private void mniChatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mniChatMouseClicked
                // TODO add your handling code here:
                LoginFrame lg = new LoginFrame();
                lg.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                lg.setVisible(false);

        }//GEN-LAST:event_mniChatMouseClicked

        private void mniDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDoiMatKhauActionPerformed
                // TODO add your handling code here:
                this.dispose();
                new DoiMatKhauJDialog(this, true).setVisible(true);
                this.setVisible(true);
                initHienThongTin();
        }//GEN-LAST:event_mniDoiMatKhauActionPerformed

        private void mniThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniThoatActionPerformed
                // TODO add your handling code here:
                if (MsgBox.confirm(this, "Bạn có chắc muốn thoát không ?")) {
                        System.exit(0);
                }
        }//GEN-LAST:event_mniThoatActionPerformed

        private void mniThongTinPhanMemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniThongTinPhanMemActionPerformed
                // TODO add your handling code here:
                new ThongTinPhanMemJDialog(this, true).setVisible(true);
        }//GEN-LAST:event_mniThongTinPhanMemActionPerformed

    private void mniDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniDangXuatActionPerformed
            // TODO add your handling code here:
            lblHinhAnh.setIcon(null);
            Auth.user = null;
            this.dispose();
            new DangNhapJDialog(this, true).setVisible(true);
            this.setVisible(true);
            initHienThongTin();
    }//GEN-LAST:event_mniDangXuatActionPerformed

    private void lblKhoHang1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKhoHang1MouseClicked
            // TODO add your handling code here:
            new KhoHangJdialog(this, true).setVisible(true);
            this.setVisible(true);
            initHienThongTin();
    }//GEN-LAST:event_lblKhoHang1MouseClicked

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(GiaoDienChinhJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(GiaoDienChinhJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(GiaoDienChinhJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(GiaoDienChinhJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
                //</editor-fold>
                //</editor-fold>
                //</editor-fold>
                //</editor-fold>
                //</editor-fold>
                //</editor-fold>
                //</editor-fold>
                //</editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new GiaoDienChinhJFrame().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JMenuBar jMenuBar1;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JLabel jlabel;
        private javax.swing.JLabel jlable;
        private javax.swing.JLabel lblChucVu;
        private javax.swing.JLabel lblDangXuatKS;
        private javax.swing.JLabel lblDangXuatLT;
        private javax.swing.JLabel lblDangXuatNS;
        private javax.swing.JLabel lblDatPhongLT;
        private javax.swing.JLabel lblDichVu;
        private javax.swing.JLabel lblDichVuKS;
        private javax.swing.JLabel lblDichVuLT;
        private javax.swing.JLabel lblDoThatLac;
        private javax.swing.JLabel lblDoThatLacQLKS;
        private javax.swing.JLabel lblDoiMatKhau;
        private javax.swing.JLabel lblDoiMatKhau1;
        private javax.swing.JLabel lblDoiMatKhau2;
        private javax.swing.JLabel lblDongHo;
        private javax.swing.JLabel lblFeedBackLT;
        private javax.swing.JLabel lblHinhAnh;
        private javax.swing.JLabel lblKhachHang;
        private javax.swing.JLabel lblKhachHangKS;
        private javax.swing.JLabel lblKhachHangLT;
        private javax.swing.JLabel lblKhoHang;
        private javax.swing.JLabel lblKhoHang1;
        private javax.swing.JLabel lblNhanVien;
        private javax.swing.JLabel lblNhanVienNS;
        private javax.swing.JLabel lblPhong;
        private javax.swing.JLabel lblPhongKS;
        private javax.swing.JLabel lblTaiKhoan;
        private javax.swing.JLabel lblTaiKhoanNS;
        private javax.swing.JLabel lblTenTaiKhoan;
        private javax.swing.JLabel lblThanhToanLT;
        private javax.swing.JLabel lblThongKe;
        private javax.swing.JLabel lblThongKeKS;
        private javax.swing.JLabel lblbackgr;
        private javax.swing.JMenu mniChat;
        private javax.swing.JMenuItem mniDangXuat;
        private javax.swing.JMenuItem mniDoiMatKhau;
        private javax.swing.JMenuItem mniThoat;
        private javax.swing.JMenuItem mniThongTinPhanMem;
        private javax.swing.JMenu mnuHeThong;
        private javax.swing.JMenu mnuTroGiup;
        private javax.swing.JPanel pnlAdmin;
        private javax.swing.JPanel pnlChucNang;
        private javax.swing.JPanel pnlHinhAnh;
        private javax.swing.JPanel pnlKS;
        private javax.swing.JPanel pnlLeTan;
        private javax.swing.JPanel pnlNhanSu;
        private javax.swing.JPanel pnlThongTinAccount;
        // End of variables declaration//GEN-END:variables

        void initHienThongTin() {
                lblTenTaiKhoan.setText(Auth.user.getMaNhanVien());
                String ChucVu = "";
                switch (Auth.user.getVaiTro()) {
                        case 1:
                                ChucVu = "Lễ Tân";
                                pnlLeTan.setVisible(true);
                                pnlKS.setVisible(false);
                                pnlNhanSu.setVisible(false);
                                pnlAdmin.setVisible(false);
                                break;
                        case 2:
                                ChucVu = "Quản lý khách sạn";
                                pnlKS.setVisible(true);
                                pnlLeTan.setVisible(false);
                                pnlNhanSu.setVisible(false);
                                pnlAdmin.setVisible(false);

                                break;
                        case 3:
                                ChucVu = "Nhân Sự";
                                pnlNhanSu.setVisible(true);
                                pnlKS.setVisible(false);
                                pnlLeTan.setVisible(false);
                                pnlAdmin.setVisible(false);
                                break;
                        default:
                                ChucVu = "Giám đốc";
                                pnlNhanSu.setVisible(false);
                                pnlKS.setVisible(false);
                                pnlLeTan.setVisible(false);
                                pnlAdmin.setVisible(true);
                                break;
                }
                lblChucVu.setText(ChucVu);
                NhanVienDAO nvDAO = new NhanVienDAO();
                String maNV = Auth.user.getMaNhanVien();
                NhanVien nv = nvDAO.selectByID(maNV);
                if (nv.getHinhAnh() != null) {
                        lblHinhAnh.setIcon(new ImageIcon(new ImageIcon(nv.getHinhAnh()).getImage().getScaledInstance(lblHinhAnh.getWidth(), lblHinhAnh.getHeight(), Image.SCALE_SMOOTH)));
                }

        }

        void LoadHinhAnh() {
                NhanVienDAO nvDAO = new NhanVienDAO();
                String maNV = Auth.user.getMaNhanVien();
                NhanVien nv = nvDAO.selectByID(maNV);
                lblHinhAnh.setIcon(new ImageIcon(new ImageIcon(nv.getHinhAnh()).getImage().getScaledInstance(196, 246, Image.SCALE_SMOOTH)));

        }
}
