/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Helper.JDBC;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Toolkit;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot3D;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author Admin
 */
public class PieChart extends javax.swing.JDialog {

        /**
         * Creates new form PieChart
         */
        public PieChart(java.awt.Frame parent, boolean modal) {
                super(parent, modal);
                initComponents();
                setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/icons/logo1.png")));
                setLocationRelativeTo(null);
                init();
        }

        void init() {
                String sqlSoDoDaTra = "select count(TinhTrang) from DoThatLac where TinhTrang = 1";
                int soDoDaTra = (int) JDBC.value(sqlSoDoDaTra);
                String sqlSoDoChuaTra = "select count(TinhTrang) from DoThatLac where TinhTrang = 0";
                int soDoChuaTra = (int) JDBC.value(sqlSoDoChuaTra);
                String sqlSoDoLienHe = "select count(TinhTrang) from DoThatLac where TinhTrang = 2";
                int soDoLienHe = (int) JDBC.value(sqlSoDoLienHe);
                int tong = soDoDaTra + soDoChuaTra + soDoLienHe;

                double phanTramSoDoDaTra = ((double) soDoDaTra / tong) * 100;
                double phanTramSoDoChuaTra = ((double) soDoChuaTra / tong) * 100;
                double phanTramSoDoLienHe = ((double) soDoLienHe / tong) * 100;

                DefaultPieDataset pieDataset = new DefaultPieDataset();
                pieDataset.setValue("Số lượng đồ đã trả : " + String.format("%.2f", phanTramSoDoDaTra), phanTramSoDoDaTra);
                pieDataset.setValue("Số lượng đồ đã liên hệ : " + String.format("%.2f", phanTramSoDoChuaTra), phanTramSoDoChuaTra);
                pieDataset.setValue("Số lượng đồ chưa trả : " + String.format("%.2f", phanTramSoDoLienHe), phanTramSoDoLienHe);
                JFreeChart chart = ChartFactory.createPieChart3D("Số lượng đồ thất lạc", pieDataset, true, true, true);
                PiePlot3D p = (PiePlot3D) chart.getPlot();
                p.setSectionPaint(0, new Color(250, 255, 250, 100));
                p.setSectionPaint(1, new Color(250, 150, 250, 100));
                p.setSectionPaint(2, new Color(100, 200, 250, 100));
                chart.getTitle().setPaint(Color.red);
                chart.setBackgroundPaint(new Color(247, 220, 111, 95));
                /*
                ChartFrame frame = new ChartFrame("Số lượng đồ thất lạc", chart);
                frame.setVisible(true);
                frame.setLocationRelativeTo(null);
                frame.setSize(600, 500);
                 */
                ChartPanel chartPanel = new ChartPanel(chart);
                pnlChart.removeAll();
                pnlChart.add(chartPanel, BorderLayout.CENTER);
                pnlChart.validate();

        }

        /**
         * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                pnlChart = new javax.swing.JPanel();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

                pnlChart.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PieChart", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
                pnlChart.setLayout(new javax.swing.BoxLayout(pnlChart, javax.swing.BoxLayout.LINE_AXIS));

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(pnlChart, javax.swing.GroupLayout.DEFAULT_SIZE, 765, Short.MAX_VALUE)
                                .addContainerGap())
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(pnlChart, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                                .addContainerGap())
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(PieChart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(PieChart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(PieChart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(PieChart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
                //</editor-fold>

                /* Create and display the form */
//                java.awt.EventQueue.invokeLater(new Runnable() {
//                        public void run() {
//                                new PieChart().setVisible(true);
//                        }
//                });
                /* Create and display the dialog */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                PieChart dialog = new PieChart(new javax.swing.JFrame(), true);
                                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                                        @Override
                                        public void windowClosing(java.awt.event.WindowEvent e) {
                                                System.exit(0);
                                        }
                                });
                                dialog.setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel pnlChart;
        // End of variables declaration//GEN-END:variables
}
